### PR TITLE
Update pflag version

### LINKED ISSUE #767: Constraint needs updating for spf13/pflag
**What steps did you take and what happened:**
When updating a plugin, the build fails because spf13/pflag is out of sync with spf13/cobra

**What did you expect to happen:**
A compilation error that was relevant to the code, not it's dependencies

**The output of the following commands will help us better understand what's going on**:
```log
...
github.com/heptio/ark-blockstore-rook/vendor/k8s.io/client-go/tools/pager                                                                                                                      
# github.com/heptio/ark-blockstore-rook/vendor/github.com/spf13/cobra                                                                                                                          
vendor/github.com/spf13/cobra/command.go:31:25: undefined: pflag.ParseErrorsWhitelist                                                                                                          
github.com/heptio/ark-blockstore-rook/vendor/github.com/heptio/ark/pkg/plugin/generated            
...
```

**Anything else you would like to add:**
An override to pflag version 1.0.2 fixed it locally, but this should be fixed here.

**Environment:**

- Ark version (use `ark version`): 0.9.3
- Kubernetes version (use `kubectl version`): not relevant
- Kubernetes installer & version: not relevant
- Cloud provider or hardware configuration: not relevant
- OS (e.g. from `/etc/os-release`): ARCH Linux

### PR DESCRIPTION
**Pull request by nrb**
Fixes #767

Signed-off-by: Nolan Brubaker <nolan@heptio.com>

### CODE REVIEW

**Comment by skriss** [comment]
Looks like `github.com/spf13/cobra` has also started doing tagged releases -- would be good to pin that as well if possible rather than using `master`. is the latest version there (`0.0.3`) compatible with this `pflag` version?

**Comment by skriss** [comment]
Heh, looks like they do them when requested by the community to deal with `dep` issues.

**Comment by nrb** [comment]
I didn't test the latest tagged version of cobra with this pflag change, but I'll do so now.

I think pinning it would be a good idea, especially for plugin authors.

**Comment by nrb** [comment]
Pushed up a new commit pinning cobra 0.0.3, since it worked with pflag 1.0.2.

**Comment by skriss** [comment]
looks like another `make update` needed

**Comment by skriss** [comment]
https://github.com/heptio/ark/issues/798 :)

**Comment by skriss** [comment]
OK if we hold off on merging this until after `backup-locations` gets merged into master?  Pretty sure there will be some merge conflicts, and I think it'll be easier to resolve from this PR.

**Comment by skriss** [comment]
Oh, @nrb you're running into another annoying thing with the CLI docs generation where it doesn't delete documentation files that should no longer exist.  Looks like you have a file for `ark bug` in there (from `master`) -- you'll need to manually delete it.

**Comment by nrb** [comment]
Oh, will fix that extra file. And it's fine with me to merge this after backup-locations.

**Comment by nrb** [comment]
Interesting, I don't see that file locally, and `make ci` passes.

```
x1c in /home/nrb/go/src/github.com/heptio/ark (git) pflag-update
% ls docs/cli-reference
ark_backup_create.md      ark_client.md           ark_describe_backups.md    ark_plugin.md            ark_restore_logs.md
ark_backup_delete.md      ark_completion.md       ark_describe.md            ark_plugin_remove.md     ark_restore.md
ark_backup_describe.md    ark_create_backup.md    ark_describe_restores.md   ark_restic.md            ark_schedule_create.md
ark_backup_download.md    ark_create.md           ark_describe_schedules.md  ark_restic_repo_get.md   ark_schedule_delete.md
ark_backup_get.md         ark_create_restore.md   ark_get_backups.md         ark_restic_repo.md       ark_schedule_describe.md
ark_backup_logs.md        ark_create_schedule.md  ark_get.md                 ark_restic_server.md     ark_schedule_get.md
ark_backup.md             ark_delete_backup.md    ark_get_restores.md        ark_restore_create.md    ark_schedule.md
ark_client_config_get.md  ark_delete.md           ark_get_schedules.md       ark_restore_delete.md    ark_server.md
ark_client_config.md      ark_delete_restore.md   ark.md                     ark_restore_describe.md  ark_version.md
ark_client_config_set.md  ark_delete_schedule.md  ark_plugin_add.md          ark_restore_get.md       README.md
```

**Comment by skriss** [comment]
Oh, my previous comment was invalid, forgot this was going into `master`.  

Is your `pflag-update` branch rebased on top of the current `upstream/master`?

**Comment by nrb** [comment]
I thought it was, but I didn't have the bug PR merged. Fixed that and reorganized the code a bit.

**Comment by nrb** [comment]
Rebased/updated to reflect backup locations
